# config.yml
debug: false
log: true
language: en_US

# 方块列表配置文件
block-list:
  normal:
    worlds:
      - "world"
  nether:
    worlds:
      - "world_nether"
  end:
    worlds:
      - "world_the_end"
